# Collaborative Filtering on MovieLens Dataset

Notebook Contents:
- User-based (user-user) collaborative filtering
- Item-based (item-item) collaborative filtering
- Evaluation
- Conclusion

Based on: [Pratiknabriya](https://github.com/pratiknabriya/Recommender-System-Collaborative-Filtering-MovieLens/blob/main/collaborative_filtering_movielense.ipynb)

### Basic Libraries

In [1]:
# Basic libraries 

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Data Set

```Python
# mounting google drive
from google.colab import drive
drive.mount('/content/gdrive')

# specify path
my_path = "/content/gdrive/My Drive/Upgrad/ml-latest-small/"

# read ratings file
ratings = pd.read_csv(my_path + 'ratings.csv')
```

In [2]:
# Read the .csv file
ratings = pd.read_csv('data/ratings.csv')

ratings.head()

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [3]:
ratings.shape

(100836, 4)

In [4]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype  
---  ------     --------------   -----  
 0   userId     100836 non-null  int64  
 1   movieId    100836 non-null  int64  
 2   rating     100836 non-null  float64
 3   timestamp  100836 non-null  int64  
dtypes: float64(1), int64(3)
memory usage: 3.1 MB


In [5]:
ratings.isna().sum()

userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

### Train-test Split

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test = train_test_split(ratings, test_size = 0.30, random_state = 42)

print(X_train.shape)
print(X_test.shape)

(70585, 4)
(30251, 4)


In [7]:
X_train.head()

userId  movieId  rating   timestamp
29183     200     8641     3.0  1229877411
24794     174      253     5.0   848487003
75202     475      165     4.5  1498031585
83815     534    46578     2.5  1459788454
10678      68     1967     2.5  1269121677

In [8]:
X_test.head()

userId  movieId  rating   timestamp
67037     432    77866     4.5  1335139641
42175     288      474     3.0   978465565
93850     599     4351     3.0  1498524542
6187       42     2987     4.0   996262677
12229      75     1610     4.0  1158989841

In [9]:
# pivot ratings into movie features
user_data = X_train.pivot(index = 'userId', columns = 'movieId', values = 'rating').fillna(0)

user_data.head()

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           4.0     0.0     4.0     0.0     0.0     4.0     0.0     0.0   
2           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
5           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  9       10      ...  190221  191005  193565  193571  193573  193579  \
userId                   ...                                                   
1           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
2           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
5           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  193581  193583  193585  193609  
userId                                   
1           0.0     0.0     0.0     0.0  
2           0.0     0.0     0.0     0.0  
3           0.0     0.0     0.0     0.0  
4           0.0     0.0     0.0     0.0  
5           0.0     0.0     0.0     0.0  

[5 rows x 8566 columns]

### Create a Copy of Train and Test Dataset
These datasets will be used for prediction and evaluation.

Dummy train will be used later for prediction of the movies which has not been rated by the user. To ignore the movies rated by the user, we will mark it as 0 during prediction. The movies not rated by user is marked as 1 for prediction.

Dummy test will be used for evaluation. To evaluate, we will only make prediction on the movies rated by the user. So, this is marked as 1. This is just opposite of dummy_train.

In [10]:
# make a copy of train and test datasets
dummy_train = X_train.copy()
dummy_test = X_test.copy()

dummy_train['rating'] = dummy_train['rating'].apply(lambda x: 0 if x > 0 else 1)   # dummy_train receive 0 if x > 0; or receive 1 for prediction
dummy_test['rating'] = dummy_test['rating'].apply(lambda x: 1 if x > 0 else 0)     # dummy_test receive 1 if x > 0; or receive 0 for evaluation

In [11]:
# The movies not rated by user is marked as 1 for prediction 
dummy_train = dummy_train.pivot(index = 'userId', columns = 'movieId', values = 'rating').fillna(1)

# The movies not rated by user is marked as 0 for evaluation 
dummy_test = dummy_test.pivot(index ='userId', columns = 'movieId', values = 'rating').fillna(0)

dummy_train.head()

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           0.0     1.0     0.0     1.0     1.0     0.0     1.0     1.0   
2           1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0   
3           1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0   
4           1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0   
5           1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0   

movieId  9       10      ...  190221  191005  193565  193571  193573  193579  \
userId                   ...                                                   
1           1.0     1.0  ...     1.0     1.0     1.0     1.0     1.0     1.0   
2           1.0     1.0  ...     1.0     1.0     1.0     1.0     1.0     1.0   
3           1.0     1.0  ...     1.0     1.0     1.0     1.0     1.0     1.0   
4           1.0     1.0  ...     1.0     1.0     1.0     1.0     1.0     1.0   
5           1.0     1.0  ...     1.0     1.0     1.0     1.0     1.0     1.0   

movieId  193581  193583  193585  193609  
userId                                   
1           1.0     1.0     1.0     1.0  
2           1.0     1.0     1.0     1.0  
3           1.0     1.0     1.0     1.0  
4           1.0     1.0     1.0     1.0  
5           1.0     1.0     1.0     1.0  

[5 rows x 8566 columns]

In [12]:
dummy_test.head()

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
5           1.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  9       10      ...  187595  189043  189111  189333  189547  189713  \
userId                   ...                                                   
1           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
2           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
5           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  190213  190219  193567  193587  
userId                                   
1           0.0     0.0     0.0     0.0  
2           0.0     0.0     0.0     0.0  
3           0.0     0.0     0.0     0.0  
4           0.0     0.0     0.0     0.0  
5           0.0     0.0     0.0     0.0  

[5 rows x 6124 columns]

# User-User Similarity Matrix

In [13]:
user_data.head()

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           4.0     0.0     4.0     0.0     0.0     4.0     0.0     0.0   
2           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
5           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  9       10      ...  190221  191005  193565  193571  193573  193579  \
userId                   ...                                                   
1           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
2           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
5           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  193581  193583  193585  193609  
userId                                   
1           0.0     0.0     0.0     0.0  
2           0.0     0.0     0.0     0.0  
3           0.0     0.0     0.0     0.0  
4           0.0     0.0     0.0     0.0  
5           0.0     0.0     0.0     0.0  

[5 rows x 8566 columns]

In [14]:
from sklearn.metrics.pairwise import cosine_similarity

# User Similarity Matrix using Cosine similarity as a similarity measure between Users
user_similarity = cosine_similarity(user_data)

# If user_similarity has a NaN element, receive zero 
user_similarity[np.isnan(user_similarity)] = 0

print('user_similarity:')
print(user_similarity)
print()
print('user_similarity shape:')
print(user_similarity.shape)

user_similarity:
[[1.         0.01799262 0.02914591 ... 0.22586534 0.12184689 0.13241346]
 [0.01799262 1.         0.         ... 0.04299081 0.03472882 0.0625667 ]
 [0.02914591 0.         1.         ... 0.00378273 0.         0.02382229]
 ...
 [0.22586534 0.04299081 0.00378273 ... 1.         0.10982639 0.21962266]
 [0.12184689 0.03472882 0.         ... 0.10982639 1.         0.05416081]
 [0.13241346 0.0625667  0.02382229 ... 0.21962266 0.05416081 1.        ]]

user_similarity shape:
(610, 610)


### Predicting the User Ratings on the Movies


In [15]:
# Calculate the predicted ratings for users based on the similarity between users and their past ratings.
user_predicted_ratings = np.dot(user_similarity, user_data)

print(user_predicted_ratings)

[[8.52008912e+01 3.99290227e+01 2.08165173e+01 ... 2.81820351e-02
  2.81820351e-02 1.57425084e-01]
 [2.45531356e+01 1.05987273e+01 2.94172315e+00 ... 8.74389309e-02
  8.74389309e-02 4.49741734e-01]
 [4.22670774e+00 2.11463396e+00 9.59320674e-01 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 ...
 [9.49265311e+01 4.92867089e+01 2.12555470e+01 ... 2.51644930e-02
  2.51644930e-02 5.92666313e-01]
 [7.50962548e+01 3.56578151e+01 1.17138113e+01 ... 0.00000000e+00
  0.00000000e+00 6.43083908e-02]
 [7.67153155e+01 3.67625117e+01 1.11564580e+01 ... 2.61466866e-01
  2.61466866e-01 8.03583319e-01]]


In [16]:
user_predicted_ratings.shape

(610, 8566)

We do not want to recommend the same movie that the user already watched. We are interested only in the movies not rated by the user, we will ignore the movies rated by the user.

This is where we will use our dummy train matrix that we previously built.

In [17]:
dummy_train.head()

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           0.0     1.0     0.0     1.0     1.0     0.0     1.0     1.0   
2           1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0   
3           1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0   
4           1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0   
5           1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0   

movieId  9       10      ...  190221  191005  193565  193571  193573  193579  \
userId                   ...                                                   
1           1.0     1.0  ...     1.0     1.0     1.0     1.0     1.0     1.0   
2           1.0     1.0  ...     1.0     1.0     1.0     1.0     1.0     1.0   
3           1.0     1.0  ...     1.0     1.0     1.0     1.0     1.0     1.0   
4           1.0     1.0  ...     1.0     1.0     1.0     1.0     1.0     1.0   
5           1.0     1.0  ...     1.0     1.0     1.0     1.0     1.0     1.0   

movieId  193581  193583  193585  193609  
userId                                   
1           1.0     1.0     1.0     1.0  
2           1.0     1.0     1.0     1.0  
3           1.0     1.0     1.0     1.0  
4           1.0     1.0     1.0     1.0  
5           1.0     1.0     1.0     1.0  

[5 rows x 8566 columns]

In [18]:
# np.multiply for cell-by-cell multiplication 

user_final_ratings = np.multiply(user_predicted_ratings, dummy_train)

user_final_ratings.head(8)

movieId     1          2          3         4          5          6       \
userId                                                                     
1         0.000000  39.929023   0.000000  1.220732  10.483532   0.000000   
2        24.553136  10.598727   2.941723  0.085473   2.773060  10.458197   
3         4.226708   2.114634   0.959321  0.066644   0.308448   2.855740   
4        50.832807  23.786786   9.793001  0.706291   6.609481  24.594138   
5        60.794262  36.875980  12.358414  2.321889  13.215004  29.323176   
6        63.618425   0.000000  17.636182  0.000000  17.553362  32.261103   
7         0.000000  33.959258  10.588660  0.679702   8.706095  30.272136   
8        77.976137   0.000000  14.884336  2.528757  16.439309  36.087439   

movieId     7         8         9          10      ...    190221    191005  \
userId                                             ...                       
1        14.082187  2.605186  4.111435  47.981999  ...  0.083324  0.036234   
2         2.308815  0.523106  0.588578  11.698251  ...  0.054182  0.112421   
3         0.518991  0.105484  0.190006   2.550762  ...  0.008707  0.000000   
4        10.881808  1.505819  2.196956  27.970658  ...  0.005910  0.065396   
5        14.149193  3.043103  2.351687  47.983608  ...  0.108995  0.000000   
6         0.000000  0.000000  5.186252   0.000000  ...  0.031335  0.000000   
7        10.546568  1.623343  3.157923  35.837547  ...  0.051544  0.043309   
8        16.987285  2.996154  3.431326   0.000000  ...  0.114327  0.000000   

movieId    193565    193571    193573    193579    193581    193583    193585  \
userId                                                                          
1        0.028182  0.032208  0.032208  0.028182  0.032208  0.028182  0.028182   
2        0.087439  0.099930  0.099930  0.087439  0.099930  0.087439  0.087439   
3        0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
4        0.050864  0.058130  0.058130  0.050864  0.058130  0.050864  0.050864   
5        0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
6        0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
7        0.033685  0.038497  0.038497  0.033685  0.038497  0.033685  0.033685   
8        0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

movieId    193609  
userId             
1        0.157425  
2        0.449742  
3        0.000000  
4        0.106328  
5        0.103332  
6        0.066077  
7        0.416012  
8        0.169650  

[8 rows x 8566 columns]

### Top 5 Movie Recommendations for the User 42

In [19]:
user_final_ratings.iloc[42].sort_values(ascending = False)[0:5]

movieId
480    87.452973
150    86.994790
457    81.930003
593    80.807548
1      61.416804
Name: 43, dtype: float64

# Item-Based Collaborative Filtering

In [20]:
movie_features = X_train.pivot(index = 'movieId', columns = 'userId', values = 'rating').fillna(0)

movie_features.head()

userId   1    2    3    4    5    6    7    8    9    10   ...  601  602  603  \
movieId                                                    ...                  
1        4.0  0.0  0.0  0.0  0.0  0.0  4.5  0.0  0.0  0.0  ...  0.0  0.0  4.0   
2        0.0  0.0  0.0  0.0  0.0  4.0  0.0  4.0  0.0  0.0  ...  0.0  4.0  0.0   
3        4.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4        0.0  0.0  0.0  0.0  0.0  3.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
5        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

userId   604  605  606  607  608  609  610  
movieId                                     
1        0.0  4.0  2.5  0.0  2.5  3.0  5.0  
2        0.0  3.5  0.0  0.0  0.0  0.0  0.0  
3        0.0  0.0  0.0  0.0  2.0  0.0  0.0  
4        0.0  0.0  0.0  0.0  0.0  0.0  0.0  
5        3.0  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 610 columns]

### Item-Item Similarity Matrix

In [21]:
from sklearn.metrics.pairwise import cosine_similarity

# Item Similarity Matrix using Cosine similarity as a similarity measure between Items
item_similarity = cosine_similarity(movie_features)

# If item_similarity has a NaN element, receive zero 
item_similarity[np.isnan(item_similarity)] = 0

print('item_similarity:')
print(item_similarity)
print()
print('item_similarity shape:')
print(item_similarity.shape)

item_similarity:
[[1.         0.3250275  0.20868811 ... 0.         0.         0.        ]
 [0.3250275  1.         0.16373912 ... 0.         0.         0.        ]
 [0.20868811 0.16373912 1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         1.         0.        ]
 [0.         0.         0.         ... 1.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]

item_similarity shape:
(8566, 8566)


### Predicting the User Ratings on the Movies

In [22]:
# Calculate the predicted ratings for items based on their features and the similarity between items.
item_predicted_ratings = np.dot(movie_features.T, item_similarity)

print(item_predicted_ratings)

[[1.70457674e+02 1.45736065e+02 1.43879168e+02 ... 4.90965204e-01
  4.90965204e-01 2.29232951e+00]
 [1.47046553e+01 1.27977597e+01 7.41114463e+00 ... 4.11059622e-01
  4.11059622e-01 2.92895445e+00]
 [4.64495934e+00 3.92745275e+00 3.15259091e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 ...
 [3.43701501e+02 3.24195971e+02 2.65563257e+02 ... 1.03906576e+00
  1.03906576e+00 1.84582165e+01]
 [2.59031967e+01 2.12250531e+01 1.32545528e+01 ... 0.00000000e+00
  0.00000000e+00 3.54245954e-01]
 [5.33648012e+02 4.18264714e+02 2.11408804e+02 ... 1.91118832e+01
  1.91118832e+01 3.78219746e+01]]


In [23]:
item_predicted_ratings.shape

(610, 8566)

In [24]:
dummy_train.shape

(610, 8566)

### Filtering the Ratings Only for the Movies not already Rated by the User for Recommendation

In [25]:
dummy_train.head()

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           0.0     1.0     0.0     1.0     1.0     0.0     1.0     1.0   
2           1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0   
3           1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0   
4           1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0   
5           1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0   

movieId  9       10      ...  190221  191005  193565  193571  193573  193579  \
userId                   ...                                                   
1           1.0     1.0  ...     1.0     1.0     1.0     1.0     1.0     1.0   
2           1.0     1.0  ...     1.0     1.0     1.0     1.0     1.0     1.0   
3           1.0     1.0  ...     1.0     1.0     1.0     1.0     1.0     1.0   
4           1.0     1.0  ...     1.0     1.0     1.0     1.0     1.0     1.0   
5           1.0     1.0  ...     1.0     1.0     1.0     1.0     1.0     1.0   

movieId  193581  193583  193585  193609  
userId                                   
1           1.0     1.0     1.0     1.0  
2           1.0     1.0     1.0     1.0  
3           1.0     1.0     1.0     1.0  
4           1.0     1.0     1.0     1.0  
5           1.0     1.0     1.0     1.0  

[5 rows x 8566 columns]

In [26]:
# np.multiply for cell-by-cell multiplication 
item_final_ratings = np.multiply(item_predicted_ratings, dummy_train)

item_final_ratings.head()

movieId     1           2          3          4          5          6       \
userId                                                                       
1         0.000000  145.736065   0.000000  17.752252  60.018339   0.000000   
2        14.704655   12.797760   7.411145   0.269430   5.804070  10.243947   
3         4.644959    3.927453   3.152591   0.227362   0.903036   4.159893   
4        82.099482   70.871325  49.487513  10.082054  34.732576  65.274992   
5        29.845750   30.143357  18.279888   9.367018  17.505036  23.594082   

movieId     7          8          9           10      ...    190221    191005  \
userId                                                ...                       
1        64.555580  56.220407  28.999703  143.817617  ...  1.537469  0.490965   
2         3.230076   4.735767   1.599833   10.960730  ...  0.461311  0.411060   
3         1.724414   0.864785   1.312176    4.381157  ...  0.047166  0.000000   
4        41.705394  29.677329  12.913699   70.165084  ...  0.069251  0.629317   
5        17.286535  13.692940   5.029116   31.156561  ...  0.694836  0.000000   

movieId    193565    193571    193573    193579    193581    193583    193585  \
userId                                                                          
1        0.490965  0.490965  0.490965  0.490965  0.490965  0.490965  0.490965   
2        0.411060  0.411060  0.411060  0.411060  0.411060  0.411060  0.411060   
3        0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
4        0.629317  0.629317  0.629317  0.629317  0.629317  0.629317  0.629317   
5        0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

movieId    193609  
userId             
1        2.292330  
2        2.928954  
3        0.000000  
4        1.033695  
5        0.537539  

[5 rows x 8566 columns]

### Top 5 Movie Recommendations for the User 42

In [27]:
item_final_ratings.iloc[42].sort_values(ascending = False)[0:5]

movieId
480    88.928798
457    78.872510
2      78.342161
150    74.121047
185    72.608642
Name: 43, dtype: float64

Just to remmember:

In [28]:
user_final_ratings.iloc[42].sort_values(ascending = False)[0:5]

movieId
480    87.452973
150    86.994790
457    81.930003
593    80.807548
1      61.416804
Name: 43, dtype: float64

# Evaluation

Evaluation will we same as you have seen above for the prediction. The only difference being, you will evaluate for the movie already rated by the User instead of predicting it for the movie not rated by the user.

In [29]:
test_user_features = X_test.pivot(index = 'userId', columns = 'movieId', values = 'rating').fillna(0)

test_user_similarity = cosine_similarity(test_user_features)

test_user_similarity[np.isnan(test_user_similarity)] = 0

print('test_user_similarity:')
print(test_user_similarity)
print()
print('test_user_similarity shape:')
print(test_user_similarity.shape)

test_user_similarity:
[[1.         0.         0.07126637 ... 0.0749648  0.         0.02105064]
 [0.         1.         0.         ... 0.02631254 0.         0.04691426]
 [0.07126637 0.         1.         ... 0.         0.         0.        ]
 ...
 [0.0749648  0.02631254 0.         ... 1.         0.06079015 0.12466251]
 [0.         0.         0.         ... 0.06079015 1.         0.02233952]
 [0.02105064 0.04691426 0.         ... 0.12466251 0.02233952 1.        ]]

test_user_similarity shape:
(610, 610)


In [30]:
user_predicted_ratings_test = np.dot(test_user_similarity, test_user_features)

print(user_predicted_ratings_test)

[[ 8.01521825  3.22701218  1.71422693 ...  0.04154912  0.
   0.        ]
 [ 1.64920152  0.91304857  0.02113666 ...  0.          0.
   0.        ]
 [ 1.07587801  0.07241296  0.1867716  ...  0.          0.
   0.        ]
 ...
 [17.86102484 10.1363879   4.48304633 ...  0.0274908   0.
   0.        ]
 [ 3.10351661  2.6934212   1.20357903 ...  0.          0.
   0.        ]
 [12.36110509  5.79632466  1.96280959 ...  0.          0.20526264
   0.23947308]]


### Testing on the Movies already Rated by the User

In [31]:
test_user_final_rating = np.multiply(user_predicted_ratings_test, dummy_test)

test_user_final_rating.head()

movieId     1       2       3       4       5       6       7       8       \
userId                                                                       
1         0.000000     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2         0.000000     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3         0.000000     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4         0.000000     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
5        28.077679     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  9       10      ...  187595  189043  189111  189333  189547  189713  \
userId                   ...                                                   
1           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
2           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
5           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  190213  190219  193567  193587  
userId                                   
1           0.0     0.0     0.0     0.0  
2           0.0     0.0     0.0     0.0  
3           0.0     0.0     0.0     0.0  
4           0.0     0.0     0.0     0.0  
5           0.0     0.0     0.0     0.0  

[5 rows x 6124 columns]

In [32]:
ratings['rating'].describe()

count    100836.000000
mean          3.501557
std           1.042529
min           0.500000
25%           3.000000
50%           3.500000
75%           4.000000
max           5.000000
Name: rating, dtype: float64

But we need to normalize the final rating values between range (0.5, 5).

In [33]:
from sklearn.preprocessing import MinMaxScaler

X = test_user_final_rating.copy() 

X = X[X > 0] # only consider non-zero values as 0 means the user haven't rated the movies

scaler = MinMaxScaler(feature_range = (0.5, 5))
scaler.fit(X)
pred = scaler.transform(X)

print(pred)

[[       nan        nan        nan ...        nan        nan        nan]
 [       nan        nan        nan ...        nan        nan        nan]
 [       nan        nan        nan ...        nan        nan        nan]
 ...
 [       nan 2.28631493        nan ...        nan        nan        nan]
 [       nan        nan        nan ...        nan        nan        nan]
 [       nan        nan        nan ...        nan        nan        nan]]


In [34]:
# total non-NaN value
total_non_nan = np.count_nonzero(~np.isnan(pred))

total_non_nan

30251

In [35]:
test = X_test.pivot(index = 'userId', columns = 'movieId', values = 'rating')

test.head()

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
5           4.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  9       10      ...  187595  189043  189111  189333  189547  189713  \
userId                   ...                                                   
1           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
2           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
5           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  190213  190219  193567  193587  
userId                                   
1           NaN     NaN     NaN     NaN  
2           NaN     NaN     NaN     NaN  
3           NaN     NaN     NaN     NaN  
4           NaN     NaN     NaN     NaN  
5           NaN     NaN     NaN     NaN  

[5 rows x 6124 columns]

In [36]:
# RMSE Score

diff_sqr_matrix = (test - pred)**2
sum_of_squares_err = diff_sqr_matrix.sum().sum() # df.sum().sum() by default ignores null values

rmse = np.sqrt(sum_of_squares_err/total_non_nan)
print(rmse)

1.5636288511022254


In [37]:
# Mean abslute error

mae = np.abs(pred - test).sum().sum()/total_non_nan

print(mae)

1.2116011629065675


It means that on an average our User-based recommendation engine is making an error of 1.2 in predicting the User ratings.

Now, let's evaluate Item-based recommendation engine.

### Using Item-Item Similarity

In [38]:
test_item_features = X_test.pivot(index = 'movieId', columns = 'userId', values = 'rating').fillna(0)

test_item_similarity = cosine_similarity(test_item_features)

test_item_similarity[np.isnan(test_item_similarity)] = 0 

print('test_item_similarity:')
print(test_item_similarity)
print()
print('test_item_similarity shape:')
print(test_item_similarity.shape)

test_item_similarity:
[[1.         0.15732306 0.09932171 ... 0.         0.         0.        ]
 [0.15732306 1.         0.         ... 0.         0.         0.        ]
 [0.09932171 0.         1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         1.        ]
 [0.         0.         0.         ... 0.         1.         1.        ]]

test_item_similarity shape:
(6124, 6124)


In [39]:
item_predicted_ratings_test = np.dot(test_item_features.T, test_item_similarity)

print(item_predicted_ratings_test)

[[1.90435509e+01 1.37292388e+01 1.20305765e+01 ... 4.19602222e-01
  0.00000000e+00 0.00000000e+00]
 [9.33282962e-01 1.09150271e+00 6.76481425e-02 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [1.34037111e+00 3.35148768e-01 5.76138709e-01 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 ...
 [6.10452867e+01 6.86734298e+01 3.74823847e+01 ... 4.19602222e-01
  0.00000000e+00 0.00000000e+00]
 [1.59448344e+00 1.48111314e+00 1.51270481e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [6.50933268e+01 5.62696921e+01 2.60485764e+01 ... 0.00000000e+00
  8.98355095e+00 8.98355095e+00]]


### Testing on the Movies already Rated by the User

In [40]:
test_item_final_rating = np.multiply(item_predicted_ratings_test, dummy_test)

test_item_final_rating.head()

movieId    1       2       3       4       5       6       7       8       \
userId                                                                      
1        0.000000     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2        0.000000     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3        0.000000     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4        0.000000     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
5        9.480468     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  9       10      ...  187595  189043  189111  189333  189547  189713  \
userId                   ...                                                   
1           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
2           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
5           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  190213  190219  193567  193587  
userId                                   
1           0.0     0.0     0.0     0.0  
2           0.0     0.0     0.0     0.0  
3           0.0     0.0     0.0     0.0  
4           0.0     0.0     0.0     0.0  
5           0.0     0.0     0.0     0.0  

[5 rows x 6124 columns]

In [41]:
ratings['rating'].describe()

count    100836.000000
mean          3.501557
std           1.042529
min           0.500000
25%           3.000000
50%           3.500000
75%           4.000000
max           5.000000
Name: rating, dtype: float64

In [42]:
from sklearn.preprocessing import MinMaxScaler

X = test_item_final_rating.copy() 
X = X[X > 0] # only consider non-zero values as 0 means the user haven't rated the movies

scaler = MinMaxScaler(feature_range = (0.5, 5))
scaler.fit(X)
pred = scaler.transform(X)

print(pred)

[[       nan        nan        nan ...        nan        nan        nan]
 [       nan        nan        nan ...        nan        nan        nan]
 [       nan        nan        nan ...        nan        nan        nan]
 ...
 [       nan 2.06051833        nan ...        nan        nan        nan]
 [       nan        nan        nan ...        nan        nan        nan]
 [       nan        nan        nan ...        nan        nan        nan]]


In [43]:
# total non-NaN value
total_non_nan = np.count_nonzero(~np.isnan(pred))

total_non_nan

30251

In [44]:
test = X_test.pivot(index = 'userId', columns = 'movieId', values = 'rating')

test.head()

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
5           4.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  9       10      ...  187595  189043  189111  189333  189547  189713  \
userId                   ...                                                   
1           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
2           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
5           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  190213  190219  193567  193587  
userId                                   
1           NaN     NaN     NaN     NaN  
2           NaN     NaN     NaN     NaN  
3           NaN     NaN     NaN     NaN  
4           NaN     NaN     NaN     NaN  
5           NaN     NaN     NaN     NaN  

[5 rows x 6124 columns]

In [45]:
# RMSE Score

diff_sqr_matrix = (test - pred)**2
sum_of_squares_err = diff_sqr_matrix.sum().sum() # df.sum().sum() by default ignores null values

rmse = np.sqrt(sum_of_squares_err/total_non_nan)

print(rmse)

2.512699212653213


In [46]:
# Mean abslute error

mae = np.abs(pred - test).sum().sum()/total_non_nan

print(mae)

2.215407217950911


It means that on an average our Item-based recommendation engine is making an error of 2.21 in predicting the User ratings.

# Conclusion

For the give dataset, the **User-based Collaborative Filtering** outperformed Item-based Collaborative Filtering.