# Linear Regression From Scratch

In [1]:
# libraries

import numpy as np
import math

Parameters for the straight line:

$$ Y = a + b*X $$

In [2]:
x_array = np.array([1,2,1,4,3])    #vector X
y_array = np.array([3,4,2,7,5])    #vector Y
n = x_array.size                   #number of elements in the matrix
print(x_array)
print(y_array)
print(n)

[1 2 1 4 3]
[3 4 2 7 5]
5


In [3]:
xy_array = x_array * y_array    #vector XY
x2_array = x_array ** 2         #vector X^2
y2_array = y_array ** 2         #vector Y^2
print(xy_array)
print(x2_array)
print(y2_array)

[ 3  8  2 28 15]
[ 1  4  1 16  9]
[ 9 16  4 49 25]


In [4]:
sx = sum(x_array)      #sum of elements of vector X
sy = sum(y_array)      #sum of elements of vector Y
sxy = sum(xy_array)    #sum of elements of vector XY
sx2 = sum(x2_array)    #sum of elements of vector X^2
sy2 = sum(y2_array)    #sum of elements of vector Y^2
print(sx, sy, sxy, sx2)

11 21 56 31


Parameters for the straight line:

$$ a = \frac{(\sum y)*(\sum x^2) - (\sum x)*(\sum x*y)}{n*(\sum x^2) - (\sum x)^2} $$
<br><br>
$$ b = \frac{n*(\sum x*y) - (\sum x)*(\sum y)}{n*(\sum x^2) - (\sum x)^2} $$

In [5]:
a = (sy*sx2 - sx*sxy)/(n*sx2 - sx**2)
print("a =", a)

b = (n*sxy - sx*sy)/(n*sx2 - sx**2)
print("b =", b)

a = 1.0294117647058822
b = 1.4411764705882353


Pearson correlation coefficient:

$$ r_{xy} = \frac{n*(\sum x*y) - (\sum x)*(\sum y)}{\sqrt{n*(\sum x^2) - (\sum x)^2}*\sqrt{n*(\sum y^2) - (\sum y)^2}} $$

In [6]:
r = (n*sxy - sx*sy)/(math.sqrt(n*sx2 - sx**2)*math.sqrt(n*sy2 - sy**2))
print("r =", r)

r2 = r**2
print("r^2 =", r2)

r = 0.9768789729654024
r^2 = 0.9542925278219394


In [7]:
r2t = r2*100

print("The variable X explains",round(r2t,2),"% of the variation in Y.")

The variable X explains 95.43 % of the variation in Y.
