# Operating on Data in Pandas

Based on Chapter 3 from *Python for Data Science Handbook*, by Jake VanderPlas.

In [1]:
import pandas as pd
import numpy as np

In [2]:
rng = np.random.RandomState(42)

ser = pd.Series(rng.randint(0, 10, 4))   # 4 random integers between 0 (inclusive) and 10 (exclusive).

ser

0    6
1    3
2    7
3    4
dtype: int32

In [3]:
ser

0    6
1    3
2    7
3    4
dtype: int32

In [4]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [5]:
# Generates a 2D array of random integers, 3 rows by 4 columns,
# random integers between 0 (inclusive) and 10 (exclusive).

df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                  columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [6]:
np.sin(df * np.pi / 4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

## Index Alignment

### Index alignment in Series

In [7]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')

population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')

In [8]:
population

California    38332521
Texas         26448193
New York      19651127
Name: population, dtype: int64

In [9]:
area

Alaska        1723337
Texas          695662
California     423967
Name: area, dtype: int64

In [10]:
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [11]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])

In [12]:
A

0    2
1    4
2    6
dtype: int64

In [13]:
B

1    1
2    3
3    5
dtype: int64

In [14]:
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [15]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

### Index alignment in DataFrame

In [16]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                 columns=list('AB'))
A

A   B
0  1  11
1  5   1

In [17]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
                 columns=list('BAC'))
B

B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [18]:
A + B

A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [19]:
fill = A.stack().mean()
A.add(B, fill_value=fill)

A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5

In [20]:
A = rng.randint(10, size=(3, 4))
A

array([[3, 8, 2, 4],
       [2, 6, 4, 8],
       [6, 1, 3, 8]])

In [21]:
A[0]

array([3, 8, 2, 4])

In [22]:
A - A[0]

array([[ 0,  0,  0,  0],
       [-1, -2,  2,  4],
       [ 3, -7,  1,  4]])

In [23]:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4

In [24]:
df.subtract(df['R'], axis=0)

Q  R  S  T
0 -5  0 -6 -4
1 -4  0 -2  2
2  5  0  2  7

# Handling Missing Data

### None: Pythonic missing data

In [25]:
vals1 = np.array([1, None, 3, 4])
vals1

array([1, None, 3, 4], dtype=object)

### NaN: Missing numerical data

In [26]:
vals2 = np.array([1, np.nan, 3, 4]) 
vals2.dtype

dtype('float64')

In [27]:
1 + np.nan

nan

In [28]:
vals2.sum(), vals2.min(), vals2.max()

(nan, nan, nan)

In [29]:
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2)  # NumPy does provide some special aggregations that will ignore these missing values.

(8.0, 1.0, 4.0)

### NaN and None in Pandas

In [30]:
pd.Series([1, np.nan, 2, None])  # because the presence of NaN values forces the Series to use a floating-point representation.

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [31]:
x = pd.Series(range(5), dtype=int)
x

0    0
1    1
2    2
3    3
4    4
dtype: int32

In [32]:
x[0] = None
x

0    NaN
1    1.0
2    2.0
3    3.0
4    4.0
dtype: float64

In [33]:
data = pd.Series([1, np.nan, 'hello', None])
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [34]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [35]:
data[data.notnull()]

0        1
2    hello
dtype: object

### Dropping null values

In [36]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [37]:
data.dropna()

0        1
2    hello
dtype: object

In [38]:
df = pd.DataFrame([[1,      np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [39]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [40]:
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [41]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [42]:
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [43]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [44]:
df.dropna(axis='columns', how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [45]:
df.dropna(axis='rows', thresh=3)  # The thresh parameter lets you specify a minimum number of non-null values for the row/column to be kept.

0    1  2   3
1  2.0  3.0  5 NaN

### Filling null values

In [46]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [47]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [48]:
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [49]:
# forward-fill
data.ffill() # specify a forward-fill to propagate the previous value forward

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [50]:
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [51]:
# back-fill
data.bfill() # specify a forward-fill to propagate the previous value forward

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [52]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [53]:
df.ffill(axis=1)

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

# Hierarchical Indexing

In [54]:
df = pd.DataFrame(np.random.rand(4, 2),
                  index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                  columns=['data1', 'data2'])
df

data1     data2
a 1  0.835031  0.810549
  2  0.650000  0.530696
b 1  0.600835  0.802305
  2  0.874195  0.185256

In [55]:
data = {('California', 2000): 33871648,
        ('California', 2010): 37253956,
        ('Texas', 2000): 20851820,
        ('Texas', 2010): 25145561,
        ('New York', 2000): 18976457,
        ('New York', 2010): 19378102}

new = pd.Series(data)

new

California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
New York    2000    18976457
            2010    19378102
dtype: int64

In [56]:
# hierarchical indices and columns
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]],
                                   names=['year', 'visit'])
columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']],
                                     names=['subject', 'type'])

# mock some data
data = np.round(np.random.randn(4, 6), 1)
data[:, ::2] *= 10
data += 37

# create the DataFrame
health_data = pd.DataFrame(data, index=index, columns=columns)
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      42.0  36.5  33.0  36.5  45.0  35.3
     2      37.0  37.4  35.0  38.5  41.0  37.2
2014 1      26.0  34.5  41.0  35.7  35.0  37.3
     2      44.0  38.2  45.0  36.6  35.0  37.0

In [57]:
health_data['Guido']

type          HR  Temp
year visit            
2013 1      33.0  36.5
     2      35.0  38.5
2014 1      41.0  35.7
     2      45.0  36.6

In [58]:
health_data['Guido', 'HR']

year  visit
2013  1        33.0
      2        35.0
2014  1        41.0
      2        45.0
Name: (Guido, HR), dtype: float64

In [59]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      42.0  36.5  33.0  36.5  45.0  35.3
     2      37.0  37.4  35.0  38.5  41.0  37.2
2014 1      26.0  34.5  41.0  35.7  35.0  37.3
     2      44.0  38.2  45.0  36.6  35.0  37.0

In [60]:
health_data.iloc[:2, :2]   # Select rows from the beginning up to, but not including, row index 2.

subject      Bob      
type          HR  Temp
year visit            
2013 1      42.0  36.5
     2      37.0  37.4

In [61]:
health_data.iloc[:3, :3]

subject      Bob       Guido
type          HR  Temp    HR
year visit                  
2013 1      42.0  36.5  33.0
     2      37.0  37.4  35.0
2014 1      26.0  34.5  41.0

In [62]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      42.0  36.5  33.0  36.5  45.0  35.3
     2      37.0  37.4  35.0  38.5  41.0  37.2
2014 1      26.0  34.5  41.0  35.7  35.0  37.3
     2      44.0  38.2  45.0  36.6  35.0  37.0

In [63]:
health_data.loc[:, ('Bob', 'HR')] # select all rows, ('Bob', 'HR')

year  visit
2013  1        42.0
      2        37.0
2014  1        26.0
      2        44.0
Name: (Bob, HR), dtype: float64

In [64]:
index = pd.MultiIndex.from_product([['a', 'c', 'b'], [1, 2]])

data2 = pd.Series(np.random.rand(6), index=index)

data2

a  1    0.601083
   2    0.971303
c  1    0.513538
   2    0.266972
b  1    0.760380
   2    0.122457
dtype: float64

In [65]:
data2.index.names = ['char', 'int']

data2

char  int
a     1      0.601083
      2      0.971303
c     1      0.513538
      2      0.266972
b     1      0.760380
      2      0.122457
dtype: float64

### Data Aggregations on Multi-Indices

In [66]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      42.0  36.5  33.0  36.5  45.0  35.3
     2      37.0  37.4  35.0  38.5  41.0  37.2
2014 1      26.0  34.5  41.0  35.7  35.0  37.3
     2      44.0  38.2  45.0  36.6  35.0  37.0

In [67]:
# Group by the 'year' level and calculate the mean
data_mean = health_data.groupby(level='year').mean()
data_mean

subject   Bob        Guido          Sue       
type       HR   Temp    HR   Temp    HR   Temp
year                                          
2013     39.5  36.95  34.0  37.50  43.0  36.25
2014     35.0  36.35  43.0  36.15  35.0  37.15

In [68]:
# Group by 'type' in the columns and calculate the mean
data_mean2 = health_data.T.groupby(level='type').mean().T
data_mean2

type               HR       Temp
year visit                      
2013 1      40.000000  36.100000
     2      37.666667  37.700000
2014 1      34.000000  35.833333
     2      41.333333  37.266667

In [69]:
# Group by 'type' in the columns and calculate the mean
data_mean3 = health_data.T.groupby(level='type').mean().T.groupby(level='year').mean()
data_mean3

type         HR   Temp
year                  
2013  38.833333  36.90
2014  37.666667  36.55