# Data Manipulation with Pandas

Based on Chapter 3 from *Python for Data Science Handbook*, by Jake VanderPlas.

In [1]:
import numpy as np
import pandas as pd

### The Pandas Series Object

In [2]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [3]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [4]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
data[1]

0.5

In [6]:
data[1:3]

1    0.50
2    0.75
dtype: float64

### Series as generalized NumPy array

In [7]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [8]:
data['b']

0.5

In [9]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [10]:
data[5]

0.5

### Series as specialized dictionary

In [11]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}

population = pd.Series(population_dict)

population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [12]:
population['California']

38332521

In [13]:
population['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

### Constructing Series objects

In [14]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [15]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [16]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [17]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: object

## The Pandas DataFrame Object

### DataFrame as a generalized NumPy array

In [18]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}

area = pd.Series(area_dict)

area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [19]:
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [20]:
states = pd.DataFrame({'population': population,
                       'area': area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [21]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [22]:
states.columns

Index(['population', 'area'], dtype='object')

### DataFrame as specialized dictionary

In [23]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

## Constructing DataFrame objects

### From a single Series object

In [24]:
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [25]:
pd.DataFrame(population, columns=['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

### From a list of dicts

In [26]:
data = [{'a': i, 'b': 2 * i}
        for i in range(3)]

pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [27]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

### From a dictionary of Series objects

In [28]:
pd.DataFrame({'population': population,
              'area': area})

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

### From a two-dimensional NumPy array

In [29]:
pd.DataFrame(np.random.rand(3, 2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

foo       bar
a  0.746670  0.059574
b  0.829785  0.735239
c  0.894563  0.927492

### From a NumPy structured array

In [30]:
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [31]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

## The Pandas Index Object

In [32]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Index([2, 3, 5, 7, 11], dtype='int64')

### Index as immutable array

In [33]:
ind[1]

3

In [34]:
ind[::2]

Index([2, 5, 11], dtype='int64')

In [35]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


## Data Selection in Series

### Series as dictionary

In [36]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [37]:
data['b']

0.5

In [38]:
'a' in data

True

In [39]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [40]:

list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [41]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

### Series as one-dimensional array

In [42]:
# slicing by explicit index
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [43]:
# slicing by implicit integer index
data[0:2]

a    0.25
b    0.50
dtype: float64

In [44]:
# masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [45]:
# fancy indexing
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

In [46]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [47]:
# explicit index when indexing
data[1]

'a'

In [48]:
# implicit index when slicing
data[1:3]

3    b
5    c
dtype: object

In [49]:
data

1    a
3    b
5    c
dtype: object

In [50]:
data.loc[1]

'a'

In [51]:
data.loc[1:3]

1    a
3    b
dtype: object

In [52]:
data

1    a
3    b
5    c
dtype: object

In [53]:
data.iloc[1]

'b'

In [54]:
data.iloc[1:3]

3    b
5    c
dtype: object

# Data Selection in DataFrame

In [55]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})

pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})

data = pd.DataFrame({'area':area, 'pop':pop})

data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [56]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [57]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [58]:
data.area is data['area']

True

In [59]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

### DataFrame as two-dimensional array

In [60]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [61]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [62]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [63]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [64]:
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [65]:
data.iloc[:3, :2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [66]:
data.loc[:'Illinois', :'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [67]:
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [68]:
data.loc[data.density > 100, ['pop', 'density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [69]:
data.iloc[0, 2] = 90
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

### Additional indexing conventions

In [70]:
data['Florida':'Illinois']

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [71]:
data[1:3]

area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

In [72]:
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [73]:
data[data.density > 100]

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

In [74]:
# Corrected data
data = np.array([
    [0.70936143, 0.23488029, 0.30445224, 0.68927288, 0.92475422, 0.82630924, 0.58798149, 0.63288447, 0.36415278, 0.24830063, 0.61563927, 0.34223401, 0.86741695, 0.68611554, 0.68930044],
    [0.60808651, 0.56796603, 0.49623607, 0.32115454, 0.30617277, 0.76150454, 0.642859, 0.26416736, 0.37650047, 0.85171977, 0.86386076, 0.46357721, 0.8715431, 0.97037945, 0.56130083],
    [0.64682958, 0.57617651, 0.87646439, 0.44740558, 0.98942307, 0.97380557, 0.98481983, 0.26412568, 0.79494542, 0.96910851, 0.79535769, 0.61218388, 0.36773023, 0.65116717, 0.42619729],
    [0.94107717, 0.9240855, 0.32608642, 0.48873634, 0.83031149, 0.6891196, 0.32186741, 0.88525873, 0.92356369, 0.39011552, 0.44122915, 0.64230049, 0.90154495, 0.33781815, 0.89301139],
    [0.52356508, 0.42569011, 0.61050939, 0.81141924, 0.82833525, 0.57066922, 0.87261075, 0.32123026, 0.86040812, 0.25760068, 0.66765117, 0.4050191, 0.26279635, 0.62357744, 0.69320655],
    [0.60323851, 0.86495236, 0.36954449, 0.3391309, 0.78257565, 0.67199629, 0.71629581, 0.66397545, 0.33308147, 0.71904428, 0.28840878, 0.76315048, 0.25290104, 0.95982256, 0.84913596],
    [0.21968934, 0.43892972, 0.93192556, 0.92968974, 0.36850702, 0.70935254, 0.3393903, 0.6453577, 0.58643086, 0.51026028, 0.84788875, 0.59780916, 0.65591447, 0.80033883, 0.38674489],
    [0.51367682, 0.38051539, 0.98933268, 0.28231457, 0.23499126, 0.76429714, 0.3253705, 0.80145551, 0.7704235, 0.39132414, 0.72999976, 0.682117, 0.42365686, 0.23424141, 0.55096506],
    [0.87801993, 0.39971423, 0.49306008, 0.31422045, 0.60209699, 0.73835126, 0.49978835, 0.52512973, 0.39225906, 0.20984305, 0.26265201, 0.86102502, 0.83768077, 0.94765324, 0.91809568],
    [0.85486612, 0.47479214, 0.76294694, 0.78635265, 0.87159301, 0.63257433, 0.90123884, 0.40607183, 0.216763, 0.80000585, 0.9292027, 0.38467495, 0.31287805, 0.245003, 0.71180443]
])

# Column names
columns = [f'sc{i:02}' for i in range(1, 16)]

# Row names
index = [f'tcg{i:02}' for i in range(1, 11)]

# Create the DataFrame
df = pd.DataFrame(data, columns=columns, index=index)

# Round the values to 2 decimal places
df = df.round(2)

df

sc01  sc02  sc03  sc04  sc05  sc06  sc07  sc08  sc09  sc10  sc11  sc12  \
tcg01  0.71  0.23  0.30  0.69  0.92  0.83  0.59  0.63  0.36  0.25  0.62  0.34   
tcg02  0.61  0.57  0.50  0.32  0.31  0.76  0.64  0.26  0.38  0.85  0.86  0.46   
tcg03  0.65  0.58  0.88  0.45  0.99  0.97  0.98  0.26  0.79  0.97  0.80  0.61   
tcg04  0.94  0.92  0.33  0.49  0.83  0.69  0.32  0.89  0.92  0.39  0.44  0.64   
tcg05  0.52  0.43  0.61  0.81  0.83  0.57  0.87  0.32  0.86  0.26  0.67  0.41   
tcg06  0.60  0.86  0.37  0.34  0.78  0.67  0.72  0.66  0.33  0.72  0.29  0.76   
tcg07  0.22  0.44  0.93  0.93  0.37  0.71  0.34  0.65  0.59  0.51  0.85  0.60   
tcg08  0.51  0.38  0.99  0.28  0.23  0.76  0.33  0.80  0.77  0.39  0.73  0.68   
tcg09  0.88  0.40  0.49  0.31  0.60  0.74  0.50  0.53  0.39  0.21  0.26  0.86   
tcg10  0.85  0.47  0.76  0.79  0.87  0.63  0.90  0.41  0.22  0.80  0.93  0.38   

       sc13  sc14  sc15  
tcg01  0.87  0.69  0.69  
tcg02  0.87  0.97  0.56  
tcg03  0.37  0.65  0.43  
tcg04  0.90  0.34  0.89  
tcg05  0.26  0.62  0.69  
tcg06  0.25  0.96  0.85  
tcg07  0.66  0.80  0.39  
tcg08  0.42  0.23  0.55  
tcg09  0.84  0.95  0.92  
tcg10  0.31  0.25  0.71